<?php $helperObj = $this->helper('Neosoft\Homepage\Helper\Data'); 
$enabled = $helperObj->isEnabled();
$isMobile = $helperObj->isMobile();
/* If slider is enabled then it will go into this condition*/
if($enabled){
  $image_url = $helperObj->imageUrl();
  if($isMobile){
    $sliders = $helperObj->getMobileSliders();
  }else{
    $sliders = $helperObj->getDesktopSliders();
  }
  /* If slider existed 1 or more than onethen it will go into this condition*/
if($sliders){ 
?>
<link rel="stylesheet" type="text/css" href="<?php echo $block->getViewFileUrl('Neosoft_Homepage::css/flexslider.css')?>">
<div class="flexslider">
  <ul class="slides">
 <?php  foreach($sliders as $k=>$slides){ 
      $image_full_path = $image_url.$slides->getImage();
  ?>
  
    <li>
      <img src="<?php echo $image_full_path; ?>" alt="<?php echo $slides->getName(); ?>" />
    </li>
    <?php } ?>
  </ul>
</div>
<script type="text/javascript">
  require(['jquery','bannerslider'],function($){
    $(window).load(function() {
        $('.flexslider').flexslider({
            animation: "fade",
            slideshowSpeed: 2000,
            itemWidth: 210,
            itemMargin: 5,
            minItems: 2,
            maxItems: 4
        });
    });
});
</script>
<?php }} ?>